using System;
using System.Collections.Generic;
using CloudBeat.Kit.Common.Json;
using CloudBeat.Kit.Common.Models;
using Newtonsoft.Json;

namespace CloudBeat.Kit.Common.Client.Dto;

/// <summary>
/// Represents the information about the status of a test case
/// </summary>
public class CaseStatusUpdateRequest
{
	/// <summary>
    /// Time when the status was received by the Gateway.
    /// </summary>
    public DateTime? Timestamp { get; set; }

    /// <summary>
    /// Gets or sets a value indicating the current run identifier
    /// </summary>
    public string RunId { get; set; }

    /// <summary>
    /// Gets or sets a value indicating the identifier of the device where the test is executed
    /// </summary>
    public string InstanceId { get; set; }

    /// <summary>
    /// Gets or sets a temporary runtime identifier of the test case, generated by the reporter. 
    /// </summary>
    public string Id { get; set; }
    
    /// <summary>
    /// Gets or sets a unique test case FQN value. 
    /// </summary>
    public string Fqn { get; set; }
    
    /// <summary>
    /// Gets or sets a parent suite FQN value. 
    /// </summary>
    public string ParentFqn { get; set; }
    
    /// <summary>
    /// Gets or sets a parent suite Id value. 
    /// </summary>
    public string ParentId { get; set; }
    
    /// <summary>
    /// Gets or sets a parent suite name. 
    /// </summary>
    public string ParentName { get; set; }
    
    /// <summary>
    /// Gets or sets a value indicating the name of the case.
    /// </summary>
    public string Name { get; set; }
	
    /// <summary>
	/// Gets or sets a value indicating the display name of the case.
	/// </summary>
	public string DisplayName { get; set; }

	/// <summary>
	/// Gets or sets a value indicating the order of execution. Nullable.
	/// </summary>
	public int? Order { get; set; }
    
	/// <summary>
	/// Gets or sets a value indicating the iteration number of the same test. Nullable.
	/// </summary>
	public int? IterationNum { get; set; }
    
	/// <summary>
	/// Gets or sets a start time of the test.
	/// </summary>
	[JsonProperty(ItemConverterType = typeof(EpochDateTimeConverter))]
	public DateTime? StartTime { get; set; }
	
	/// <summary>
	/// Gets or sets an end time of the test.
	/// </summary>
	[JsonProperty(ItemConverterType = typeof(EpochDateTimeConverter))]
	public DateTime? EndTime { get; set; }
	
	/// <summary>
    /// Gets or sets a value indicating the current progress of the case. Nullable.
    /// </summary>
    public float? Progress { get; set; }
    
    /// <summary>
    /// Get or sets the current execution status of the test.
    /// </summary>
    public RunStatusEnum RunStatus { get; set; }
    
    /// <summary>
    /// Get or sets a status of the finished test.
    /// </summary>
    [JsonProperty(ItemConverterType = typeof(StatusConverter))]
    public TestStatusEnum? TestStatus { get; set; }

    /// <summary>
    /// Get or sets a value indicating re-run count of the test, if occured.
    /// </summary>
    public int? ReRunCount { get; set; }

    /// <summary>
    /// Get or sets a failure reason of the finished test, if set. Nullable.
    /// </summary>
    public long? FailureReasonId { get; set; }
    
    /// <summary>
    /// Gets or sets the collection with results of failed iterations.
    /// </summary>
    public FailureResult[] Failures { get; set; }
    
    /// <summary>
    /// Gets or sets the standard output of the finished test.
    /// </summary>
    public string StandardOutput { get; set; }
    
    /// <summary>
    /// Gets or sets the error output of the finished test.
    /// </summary>
    public string ErrorOutput { get; set; }
    
    /// <summary>
    /// Gets or sets a testing framework used in the project.
    /// </summary>
    public string Framework { get; set; }
    
    /// <summary>
    /// Gets or sets a programming language of the test project.
    /// </summary>
    public string Language { get; set; }
    
    /// <summary>
    /// Gets or sets a test case context (arguments, test data, parameters, etc.).
    /// </summary>
    public Dictionary<string, object> Context { get; set; }
    
    /// <summary>
    /// Gets or sets a test capabilities (browserName, deviceName, etc.).
    /// </summary>
    public Dictionary<string, object> Capabilities { get; set; }
}