using System;
using CloudBeat.Kit.Common.Json;
using CloudBeat.Kit.Common.Models;
using Newtonsoft.Json;

namespace CloudBeat.Kit.Common.Client.Dto;

/// <summary>
/// Represents the information about the status of a test case
/// </summary>
public class SuiteStatusUpdateRequest
{
    /// <summary>
    /// Time when the status was received by the Gateway.
    /// </summary>
    public DateTime? Timestamp { get; set; }

    /// <summary>
    /// Gets or sets a value indicating the current run identifier
    /// </summary>
    public string RunId { get; set; }

    /// <summary>
    /// Gets or sets a value indicating the identifier of the device where the test is executed
    /// </summary>
    public string InstanceId { get; set; }

    /// <summary>
    /// Gets or sets a temporary runtime identifier of the suite, generated by the reporter. 
    /// </summary>
    public string Id { get; set; }
    
    /// <summary>
    /// Gets or sets a unique test suite FQN value. 
    /// </summary>
    public string Fqn { get; set; }
    
    /// <summary>
    /// Gets or sets a parent suite FQN value. 
    /// </summary>
    public string ParentFqn { get; set; }
    
    /// <summary>
    /// Gets or sets a parent suite Id value. 
    /// </summary>
    public string ParentId { get; set; }
    
    /// <summary>
    /// Gets or sets a parent suite name. 
    /// </summary>
    public string ParentName { get; set; }

    /// <summary>
    /// Gets or sets a value indicating the name of the suite.
    /// </summary>
    public string Name { get; set; }
	
    /// <summary>
	/// Gets or sets a value indicating the display name of the suite.
	/// </summary>
	public string DisplayName { get; set; }
    
	/// <summary>
	/// Gets or sets a start time of the test suite execution.
	/// </summary>
	[JsonProperty(ItemConverterType = typeof(EpochDateTimeConverter))]
	public DateTime? StartTime { get; set; }
	
	/// <summary>
	/// Gets or sets an end time of the test suite execution.
	/// </summary>
	[JsonProperty(ItemConverterType = typeof(EpochDateTimeConverter))]
	public DateTime? EndTime { get; set; }
	
    /// <summary>
    /// Get or sets the current execution status of the suite.
    /// </summary>
    public RunStatusEnum RunStatus { get; set; }
    
    /// <summary>
    /// Get or sets a status of the finished suite.
    /// </summary>
    [JsonProperty(ItemConverterType = typeof(StatusConverter))]
    public TestStatusEnum? TestStatus { get; set; }

    /// <summary>
    /// Gets or sets the collection with results of failed iterations.
    /// </summary>
    public FailureResult[] Failures { get; set; }
    
    /// <summary>
    /// Gets or sets the standard output of the finished suite.
    /// </summary>
    public string StandardOutput { get; set; }
    
    /// <summary>
    /// Gets or sets the error output of the finished suite.
    /// </summary>
    public string ErrorOutput { get; set; }
    
    /// <summary>
    /// Gets or sets a testing framework used in the project.
    /// </summary>
    public string Framework { get; set; }
    
    /// <summary>
    /// Gets or sets a programming language of the test project.
    /// </summary>
    public string Language { get; set; }
}