using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CloudBeat.Kit.Common.Models
{
	public class TestRun
	{
		private readonly string _id;
		private readonly bool _autoGeneratedId;

		public TestRun()
		{
			_id = Guid.NewGuid().ToString();
			_autoGeneratedId = true;
		}

		public TestRun(string id)
		{
			_id = id;
			_autoGeneratedId = false;
		}
		public string Id => this._id;

		public bool AutoGenerated => this._autoGeneratedId;
	}
}
