using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CloudBeat.Kit.Common.Models
{
	public class TestInstance
	{
		private readonly TestRun _run;
		private readonly string _id;
		private readonly bool _autoGeneratedId = false;
		private readonly Dictionary<string, string> _attributes;
		public TestRun Run => _run;
		public string Id => _id;
		public string RunId => _run?.Id;
		public bool AutoGenerated => _autoGeneratedId;
		public RunStatusEnum Status { get; set; }
		public Dictionary<string, string> Attributes => _attributes;

		public TestInstance(string runId, string instanceId) : this(runId, instanceId, null) { }

		public TestInstance(string runId, string instanceId, Dictionary<string, string> attributes)
		{
			if (runId == null)
				_run = new TestRun();
			if (instanceId == null)
			{
				_id = Guid.NewGuid().ToString();
				_autoGeneratedId = true;
			}
				
			if (attributes == null)
				_attributes = new Dictionary<string, string>();
		}
	}
}
